name: CI-CD
on: [push]
jobs:
  lint_and_test:
  runs-on: ubuntu-latest
  steps:
  -name: Set uo python
  uses: action/setup-python@v2
  with: 
      python-version: 3.10.6

  -name: Check out repository
  uses: actions/checkout@v2

  -name: Install Poetry
  uses: snok/install-poetry@v1
  with: 
      virtualenvs-in-project: true

  -name: Load cached venv
  id: cached-poetry-dependencies
  uses: actions/cache@v2
  with: 
      path: .venv
      key: venv-${{ hashFiles('**/poetry.lock') }}

  -name: Install dependencies
  if: steps.cached-poetry-dependencies.outputs.cached-hit != 'true'
  run: poetry  install --no-interaction

  -name: lint
  run: poetry run make lint

  -name: Test
  run: poetry run make test